import Foundation
import AppKit
import LAMMPSCore

final class ContentViewModel: ObservableObject {
    @Published var frames: [[Arv]] = []
    @Published var frameIndex: Int = 0
    @Published var generation: Int = 0   // bumped per file load, drives GPU re-upload
    @Published var sourceName: String = ""
    @Published var showInspector = false
    @Published var cameraResetToken = 0   // bumped by inspector's Reset Camera

    /// The frame currently on screen.
    var atoms: [Arv] { frames.indices.contains(frameIndex) ? frames[frameIndex] : [] }

    /// Load the bundled example trajectory (a Lennard-Jones argon melt,
    /// `lj_melt.xyz`, generated by the also-bundled `lj_melt.in` deck).
    func runSimulationAndDisplayResults() {
        guard frames.isEmpty else { return }   // don't clobber a user-loaded file
        guard let text = loadTrajectoryText() else {
            print("ContentViewModel: no bundled trajectory resource found")
            return
        }
        show(XYZParser.parseFrames(text), name: "LJ argon melt (bundled example)")
    }

    private func show(_ parsed: [[Arv]], name: String) {
        frames = parsed
        frameIndex = max(0, parsed.count - 1)   // open at the final state
        generation += 1
        sourceName = name
    }

    // MARK: - File menu

    /// File ▸ Load File…: open any XYZ / extended-XYZ trajectory from disk.
    func loadFilePanel() {
        let panel = NSOpenPanel()
        panel.message = "Choose an XYZ / extended-XYZ trajectory or dump file"
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = false
        guard panel.runModal() == .OK, let url = panel.url else { return }
        load(url: url)
    }

    func load(url: URL) {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else {
            Self.alert("Could not read \(url.lastPathComponent)",
                       info: "The file could not be opened as text.")
            return
        }
        let parsed = XYZParser.parseFrames(text)
        guard !parsed.isEmpty else {
            Self.alert("No atoms found in \(url.lastPathComponent)",
                       info: "MDEngine reads XYZ / extended-XYZ frames: a line with the atom "
                           + "count, a comment line, then one `element x y z` row per atom. "
                           + "Trajectories open at their final frame — scrub with the timeline.")
            return
        }
        show(parsed, name: url.lastPathComponent)
    }

    /// File ▸ Export File…: write the displayed frame back out as XYZ.
    func exportFilePanel() {
        guard !atoms.isEmpty else { return }
        let panel = NSSavePanel()
        panel.message = "Export the displayed frame as XYZ"
        panel.nameFieldStringValue = "frame.xyz"
        guard panel.runModal() == .OK, let url = panel.url else { return }

        var text = "\(atoms.count)\nExported from MDEngine — \(sourceName)\n"
        for a in atoms {
            text += "\(a.element) \(a.x) \(a.y) \(a.z)\n"
        }
        do {
            try text.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            Self.alert("Export failed", info: error.localizedDescription)
        }
    }

    // MARK: - Helpers

    private func loadTrajectoryText() -> String? {
        if let url = Bundle.module.url(forResource: "lj_melt", withExtension: "xyz"),
           let text = try? String(contentsOf: url) {
            return text
        }
        return nil
    }

    private static func alert(_ message: String, info: String) {
        let a = NSAlert()
        a.messageText = message
        a.informativeText = info
        a.runModal()
    }
}
