import Foundation
import AppKit
import LAMMPSCore

final class ContentViewModel: ObservableObject {
    @Published var frames: [[Arv]] = []
    @Published var frameIndex: Int = 0
    @Published var generation: Int = 0   // bumped per file load, drives GPU re-upload
    @Published var sourceName: String = ""
    @Published var showInspector = false
    @Published var cameraResetToken = 0   // bumped by inspector's Reset Camera

    // MARK: Playback
    @Published var isPlaying = false
    @Published var loopPlayback = UserDefaults.standard.bool(forKey: "loopPlayback") {
        didSet { UserDefaults.standard.set(loopPlayback, forKey: "loopPlayback") }
    }
    private var playTimer: Timer?

    // MARK: Live following of a growing trajectory file
    @Published var isFollowingFile = false
    private var watchedURL: URL?
    private var watchedSize: Int = -1
    private var watchTimer: Timer?

    /// The frame currently on screen.
    var atoms: [Arv] { frames.indices.contains(frameIndex) ? frames[frameIndex] : [] }

    /// Load the bundled example trajectory (a Lennard-Jones argon melt,
    /// `lj_melt.xyz`, generated by the also-bundled `lj_melt.in` deck).
    func runSimulationAndDisplayResults() {
        guard frames.isEmpty else { return }   // don't clobber a user-loaded file
        guard let text = loadTrajectoryText() else {
            print("ContentViewModel: no bundled trajectory resource found")
            return
        }
        show(XYZParser.parseFrames(text), name: "LJ argon melt (bundled example)")
    }

    private func show(_ parsed: [[Arv]], name: String) {
        frames = parsed
        frameIndex = max(0, parsed.count - 1)   // open at the final state
        generation += 1
        sourceName = name
    }

    // MARK: - Playback

    func togglePlayback() {
        isPlaying ? stopPlayback() : startPlayback()
    }

    func startPlayback() {
        guard frames.count > 1 else { return }
        isPlaying = true
        playTimer?.invalidate()
        playTimer = Timer.scheduledTimer(withTimeInterval: 0.1, repeats: true) { [weak self] _ in
            self?.stepPlayback()
        }
    }

    func stopPlayback() {
        isPlaying = false
        playTimer?.invalidate()
        playTimer = nil
    }

    private func stepPlayback() {
        if frameIndex < frames.count - 1 {
            frameIndex += 1
        } else if loopPlayback {
            frameIndex = 0
        } else {
            stopPlayback()
        }
    }

    // MARK: - Live following

    /// Poll the loaded file; when a running simulation appends frames, re-parse
    /// (the readers are safe on in-flight files) and extend the timeline in
    /// place — no re-loading by the user. Camera and scrub position are kept;
    /// if the user was at the final frame, follow the new final frame.
    private func watch(url: URL) {
        watchTimer?.invalidate()
        watchedURL = url
        watchedSize = fileSize(url)
        isFollowingFile = true
        watchTimer = Timer.scheduledTimer(withTimeInterval: 2.0, repeats: true) { [weak self] _ in
            self?.refreshFromWatchedFile()
        }
    }

    private func refreshFromWatchedFile() {
        guard let url = watchedURL else { return }
        let size = fileSize(url)
        guard size != watchedSize else { return }
        watchedSize = size
        guard size < 512_000_000 else { return }   // don't re-parse huge files every tick
        guard let text = try? String(contentsOf: url, encoding: .utf8) else { return }
        let parsed = TrajectoryReader.parseFrames(text)
        guard parsed.count != frames.count, !parsed.isEmpty else { return }
        let wasAtEnd = frameIndex >= frames.count - 1
        frames = parsed
        generation += 1
        frameIndex = wasAtEnd ? parsed.count - 1 : min(frameIndex, parsed.count - 1)
    }

    private func fileSize(_ url: URL) -> Int {
        ((try? FileManager.default.attributesOfItem(atPath: url.path))?[.size] as? Int) ?? -1
    }

    // MARK: - File menu

    /// File ▸ Load File…: open any XYZ / extended-XYZ trajectory from disk.
    func loadFilePanel() {
        let panel = NSOpenPanel()
        panel.message = "Choose a trajectory: XYZ / extended-XYZ or native LAMMPS dump"
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = false
        guard panel.runModal() == .OK, let url = panel.url else { return }
        load(url: url)
    }

    func load(url: URL) {
        guard let text = try? String(contentsOf: url, encoding: .utf8) else {
            Self.alert("Could not read \(url.lastPathComponent)",
                       info: "The file could not be opened as text.")
            return
        }
        let parsed = TrajectoryReader.parseFrames(text)
        guard !parsed.isEmpty else {
            Self.alert("No atoms found in \(url.lastPathComponent)",
                       info: "MDEngine reads XYZ / extended-XYZ and native LAMMPS dump files "
                           + "(ITEM: TIMESTEP blocks from `dump atom`/`dump custom`). "
                           + "Trajectories open at their final frame — scrub with the timeline.")
            return
        }
        show(parsed, name: url.lastPathComponent)
        watch(url: url)
    }

    /// File ▸ Export File…: write the displayed frame back out as XYZ.
    func exportFilePanel() {
        guard !atoms.isEmpty else { return }
        let panel = NSSavePanel()
        panel.message = "Export the displayed frame as XYZ"
        panel.nameFieldStringValue = "frame.xyz"
        guard panel.runModal() == .OK, let url = panel.url else { return }

        var text = "\(atoms.count)\nExported from MDEngine — \(sourceName)\n"
        for a in atoms {
            text += "\(a.element) \(a.x) \(a.y) \(a.z)\n"
        }
        do {
            try text.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            Self.alert("Export failed", info: error.localizedDescription)
        }
    }

    // MARK: - Helpers

    private func loadTrajectoryText() -> String? {
        if let url = Bundle.module.url(forResource: "lj_melt", withExtension: "xyz"),
           let text = try? String(contentsOf: url) {
            return text
        }
        return nil
    }

    private static func alert(_ message: String, info: String) {
        let a = NSAlert()
        a.messageText = message
        a.informativeText = info
        a.runModal()
    }
}
