import Foundation
import AppKit
import LAMMPSCore

final class ContentViewModel: ObservableObject {
    @Published var frames: [[Arv]] = []
    @Published var frameIndex: Int = 0
    @Published var generation: Int = 0   // bumped per file load, drives GPU re-upload
    @Published var sourceName: String = ""
    @Published var showInspector = false
    @Published var cameraResetToken = 0   // bumped by inspector's Reset Camera

    // MARK: Recent files (File ▸ Open Recent)
    @Published var recentFiles: [String] =
        UserDefaults.standard.stringArray(forKey: "recentFiles") ?? []

    private func noteRecent(_ url: URL) {
        var list = recentFiles.filter { $0 != url.path }
        list.insert(url.path, at: 0)
        recentFiles = Array(list.prefix(10))
        UserDefaults.standard.set(recentFiles, forKey: "recentFiles")
    }

    func openRecent(_ path: String) {
        guard FileManager.default.fileExists(atPath: path) else {
            recentFiles.removeAll { $0 == path }
            UserDefaults.standard.set(recentFiles, forKey: "recentFiles")
            Self.alert("File not found", info: "\(path) no longer exists; removed from Open Recent.")
            return
        }
        load(url: URL(fileURLWithPath: path))
    }

    func clearRecents() {
        recentFiles = []
        UserDefaults.standard.set(recentFiles, forKey: "recentFiles")
    }

    // MARK: Playback
    @Published var isPlaying = false
    @Published var loopPlayback = UserDefaults.standard.bool(forKey: "loopPlayback") {
        didSet { UserDefaults.standard.set(loopPlayback, forKey: "loopPlayback") }
    }
    private var playTimer: Timer?

    // MARK: Live following of a growing trajectory file
    @Published var isFollowingFile = false
    private var watchedURL: URL?
    private var watchedSize: Int = -1
    private var watchTimer: Timer?

    /// The frame currently on screen.
    var atoms: [Arv] { frames.indices.contains(frameIndex) ? frames[frameIndex] : [] }

    /// Load the bundled example trajectory (a Lennard-Jones argon melt,
    /// `lj_melt.xyz`, generated by the also-bundled `lj_melt.in` deck).
    func runSimulationAndDisplayResults() {
        guard frames.isEmpty else { return }   // don't clobber a user-loaded file
        guard let text = loadTrajectoryText() else {
            print("ContentViewModel: no bundled trajectory resource found")
            return
        }
        show(XYZParser.parseFrames(text), name: "LJ argon melt (bundled example)")
    }

    private func show(_ parsed: [[Arv]], name: String) {
        frames = parsed
        frameIndex = max(0, parsed.count - 1)   // open at the final state
        generation += 1
        sourceName = name
    }

    // MARK: - Playback

    /// Frames per second while playing; the speed bar above the play button
    /// drives this. Persisted, and applied live mid-playback.
    @Published var playbackFPS: Double = max(1, min(60, UserDefaults.standard.object(forKey: "playbackFPS") as? Double ?? 10)) {
        didSet {
            UserDefaults.standard.set(playbackFPS, forKey: "playbackFPS")
            if isPlaying { startPlayback() }
        }
    }

    func togglePlayback() {
        isPlaying ? stopPlayback() : startPlayback()
    }

    func startPlayback() {
        guard frames.count > 1 else { return }
        isPlaying = true
        playTimer?.invalidate()
        playTimer = Timer.scheduledTimer(withTimeInterval: 1 / max(1, playbackFPS),
                                         repeats: true) { [weak self] _ in
            self?.stepPlayback()
        }
    }

    func stopPlayback() {
        isPlaying = false
        playTimer?.invalidate()
        playTimer = nil
    }

    private func stepPlayback() {
        if frameIndex < frames.count - 1 {
            frameIndex += 1
        } else if loopPlayback {
            frameIndex = 0
        } else {
            stopPlayback()
        }
    }

    // MARK: - Live following

    /// Poll the loaded file; when a running simulation appends frames, re-parse
    /// (the readers are safe on in-flight files) and extend the timeline in
    /// place — no re-loading by the user. Camera and scrub position are kept;
    /// if the user was at the final frame, follow the new final frame.
    private func watch(url: URL, knownSize: Int) {
        watchTimer?.invalidate()
        watchedURL = url
        watchedSize = knownSize
        isFollowingFile = true
        // Poll slower for big files: a full re-parse costs time proportional
        // to size, so the interval scales well past the parse cost
        // (2s small, ~45s at 350MB) to avoid burning a core continuously.
        let interval = max(2.0, Double(knownSize) / 8_000_000)
        watchTimer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            self?.refreshFromWatchedFile()
        }
    }

    private func refreshFromWatchedFile() {
        guard let url = watchedURL, !refreshInFlight else { return }
        let size = fileSize(url)
        guard size != watchedSize, size < 1_000_000_000 else { return }
        watchedSize = size
        refreshInFlight = true
        parseQueue.async { [weak self] in
            let text = try? String(contentsOf: url, encoding: .utf8)
            let parsed = text.map(TrajectoryReader.parseFrames) ?? []
            DispatchQueue.main.async {
                guard let self else { return }
                self.refreshInFlight = false
                guard self.watchedURL == url,                    // not replaced meanwhile
                      parsed.count != self.frames.count, !parsed.isEmpty else { return }
                let wasAtEnd = self.frameIndex >= self.frames.count - 1
                self.frames = parsed
                self.generation += 1
                self.frameIndex = wasAtEnd ? parsed.count - 1 : min(self.frameIndex, parsed.count - 1)
            }
        }
    }

    private func fileSize(_ url: URL) -> Int {
        ((try? FileManager.default.attributesOfItem(atPath: url.path))?[.size] as? Int) ?? -1
    }

    // MARK: - File menu

    /// File ▸ Load File…: open any XYZ / extended-XYZ trajectory from disk.
    func loadFilePanel() {
        let panel = NSOpenPanel()
        panel.message = "Choose a trajectory: XYZ / extended-XYZ or native LAMMPS dump"
        panel.canChooseDirectories = false
        panel.allowsMultipleSelection = false
        guard panel.runModal() == .OK, let url = panel.url else { return }
        load(url: url)
    }

    /// Parsing happens OFF the main thread — large trajectories must never
    /// beachball the app (a 343MB in-flight dump did exactly that once).
    func load(url: URL) {
        let size = fileSize(url)
        guard size < 2_000_000_000 else {
            Self.alert("\(url.lastPathComponent) is \(size / 1_000_000) MB",
                       info: "MDEngine loads whole trajectories into memory (limit 2 GB). "
                           + "Shrink it first: mdengine decimate <file> --every N")
            return
        }
        sourceName = "Loading \(url.lastPathComponent)…"
        parseQueue.async { [weak self] in
            let text = try? String(contentsOf: url, encoding: .utf8)
            let parsed = text.map(TrajectoryReader.parseFrames) ?? []
            DispatchQueue.main.async {
                guard let self else { return }
                guard text != nil else {
                    self.sourceName = ""
                    Self.alert("Could not read \(url.lastPathComponent)",
                               info: "The file could not be opened as text.")
                    return
                }
                guard !parsed.isEmpty else {
                    self.sourceName = ""
                    Self.alert("No atoms found in \(url.lastPathComponent)",
                               info: "MDEngine reads XYZ / extended-XYZ and native LAMMPS dump files "
                                   + "(ITEM: TIMESTEP blocks from `dump atom`/`dump custom`). "
                                   + "Trajectories open at their final frame — scrub with the timeline.")
                    return
                }
                self.show(parsed, name: url.lastPathComponent)
                self.noteRecent(url)
                self.watch(url: url, knownSize: size)
            }
        }
    }

    private let parseQueue = DispatchQueue(label: "mdengine.parse", qos: .userInitiated)
    private var refreshInFlight = false

    /// File ▸ Export File…: write the displayed frame back out as XYZ.
    func exportFilePanel() {
        guard !atoms.isEmpty else { return }
        let panel = NSSavePanel()
        panel.message = "Export the displayed frame as XYZ"
        panel.nameFieldStringValue = "frame.xyz"
        guard panel.runModal() == .OK, let url = panel.url else { return }

        var text = "\(atoms.count)\nExported from MDEngine — \(sourceName)\n"
        for a in atoms {
            text += "\(a.element) \(a.x) \(a.y) \(a.z)\n"
        }
        do {
            try text.write(to: url, atomically: true, encoding: .utf8)
        } catch {
            Self.alert("Export failed", info: error.localizedDescription)
        }
    }

    // MARK: - Helpers

    private func loadTrajectoryText() -> String? {
        if let url = Bundle.module.url(forResource: "lj_melt", withExtension: "xyz"),
           let text = try? String(contentsOf: url) {
            return text
        }
        return nil
    }

    private static func alert(_ message: String, info: String) {
        let a = NSAlert()
        a.messageText = message
        a.informativeText = info
        a.runModal()
    }
}
